/*
 * Copyright 2016 Kik Interactive, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.kik.config.ice.sink;

import com.kik.config.ice.naming.SimpleConfigNamingStrategy;
import java.util.Optional;

/**
 * Interface via which an object may provide a means to fire configuration change events into the system.
 *
 * @param <T> The type of event for the sink
 */
public interface ConfigEventSink<T>
{
    /**
     * Raises a configuration change event in the config system.
     *
     * @param configName Name of the configuration element, as generated by the {@link SimpleConfigNamingStrategy} used
     *                   in the config system.
     * @param valueOpt   Value that the config entry is to be changed to. Empty optional implies the value has been
     *                   removed (i.e. is no longer configured)
     */
    void fireEvent(String configName, Optional<T> valueOpt);
}
