package com.kik.config.ice.internal;

import java.lang.reflect.Method;
import java.lang.reflect.Type;
import java.util.Objects;
import java.util.Optional;

/**
 * Generated by a ConfigDescriptorFactory. This class is primarily a data class, intended to hold the static config
 * details determined by reflection on a component's Config interface.
 */
public class ConfigDescriptor
{
    private final Method method;
    private final String name;
    private final Type type;
    private final boolean isObservable;
    private final Optional<String> scopeOpt;
    private final Optional<String> defaultValueOpt;

    /**
     * Package-Private to ensure only factory creates these.
     */
    ConfigDescriptor(Method method, String name, Type type, boolean isObservable, Optional<String> scopeOpt, Optional<String> defaultValueOpt)
    {
        this.method = method;
        this.name = name;
        this.type = type;
        this.isObservable = isObservable;
        this.scopeOpt = scopeOpt;
        this.defaultValueOpt = defaultValueOpt;
    }

    public Method getMethod()
    {
        return method;
    }

    public String getConfigName()
    {
        return name;
    }

    public Type getConfigType()
    {
        return type;
    }

    public boolean isObservable()
    {
        return isObservable;
    }

    public Optional<String> getScope()
    {
        return scopeOpt;
    }

    public Optional<String> getDefaultValue()
    {
        return defaultValueOpt;
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(method, scopeOpt);
    }

    @Override
    public boolean equals(Object obj)
    {
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        final ConfigDescriptor other = (ConfigDescriptor) obj;
        return Objects.equals(this.method, other.method)
            && Objects.equals(this.scopeOpt, other.scopeOpt);
    }

}
